name: Build
on: [push]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          command: buildozer android debug
          repository_root: .
      - uses: actions/upload-artifact@v2
        with:
          name: DealExchange-APK
          path: bin/*.apk
